application/cmapp/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from .views import *

app_name = 'project'
urlpatterns = [
	path('', projects.as_view(), name = 'projects'),
	path('project/<slug:slug>', projectdetail.as_view(), name = 'projectdetail'),
	path('todomark/<int:id>/update_mark_todo', views.update_mark_todo, name = 'update_mark_todo'),
	path('note/<int:id>/add_note_in_project', views.add_note_in_project, name = 'add_note_in_project'),
	path('delete/<int:id>/note', views.noteDelete, name='noteDelete'),
	path('budget/<int:id>/add_budget_in_project', views.add_budget_in_project, name = 'add_budget_in_project'),
	path('todo/<int:id>/todofinished', views.todofinished, name = 'todofinished'),
	path('milestone/<int:id>/milestonefinished', views.milestonefinished, name = 'milestonefinished'),
	path('add/project', projectCreate.as_view(), name = 'projectCreate'),
	path('add/notestoproject', TodoProjectCreate.as_view(), name = 'TodoProjectCreate'),
	path('activate_milestone/<int:id>/project', views.activate_milestone, name = 'activate_milestone'),
	path('deactivate_milestone/<int:id>/project', views.deactivate_milestone, name = 'deactivate_milestone'),
]

cm_hispam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('application.cmapp.urls')),
    # path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

application/cmapp/models.py
from django.db import models
from autoslug import AutoSlugField
from tinymce.models import HTMLField
from simple_history.models import HistoricalRecords
from django_countries.fields import CountryField
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User
from djmoney.models.fields import MoneyField

class Area(models.Model):
    area_title = models.CharField(max_length=255, verbose_name='Area')
    responsable = models.CharField(max_length=255, verbose_name='Lider Area')

    def __str__(self):
        return self.area_title

    class Meta:
        verbose_name = 'Area'
        verbose_name_plural = 'Areas'
        ordering = ['-id']

class Collaborator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Nombre')
    country = CountryField(blank_label='(seleccionar país)', verbose_name='País')
    area = models.ForeignKey(Area, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "%s %s" % ( self.user.first_name, self.user.last_name )

    class Meta:
        verbose_name = 'Colaborador'
        verbose_name_plural = 'Colaboradores'
        ordering = ['-id']

class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='title', always_update=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Categoria'
        ordering = ['-id']

class Project(models.Model):
    project_title = models.CharField(max_length=200, unique=True, verbose_name='Titulo')
    slug = AutoSlugField(populate_from='project_title', always_update=True, null=True)
    year = models.IntegerField(null=True)
    area = models.ManyToManyField(Area, verbose_name='Area')
    collaborator = models.ManyToManyField(Collaborator, related_name='Colaborador', verbose_name='Colaboradores')
    category = models.ManyToManyField(Category, related_name='Categoria', verbose_name='Categorías')
    # tags = TaggableManager()
    resume = HTMLField()
    pub_date = models.DateTimeField(auto_now_add=True)
    planned_date = models.DateField(null=True, verbose_name='Fecha Planificada')
    done_date = models.DateField(null=True, verbose_name='Fecha de termino Real', blank=True)
    state = models.BooleanField(blank=True, null=True, default=False, verbose_name='Terminando?')
    display_milestone = models.BooleanField(blank=True, null=True, default=False, verbose_name='Mostrar Hitos en Template')
    history = HistoricalRecords()

    def __str__(self):
        return self.project_title

    class Meta:
        verbose_name = 'Proyecto'
        ordering = ['-id']

class Budget(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    budget_title = models.CharField(max_length=200, unique=True, verbose_name='Titulo')
    budget_owner = models.ForeignKey(Collaborator, on_delete=models.CASCADE, null=True, blank=True, verbose_name='OT Manager')
    area = models.ForeignKey(Area, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Area')
    pub_date = models.DateTimeField(auto_now_add=True)
    money = MoneyField(max_digits=10, decimal_places=2, null=True, default_currency=None)

    CAPEX = 'Capex'
    OPEX = 'Opex'
    TYPE_CHOICES = [
        (CAPEX, 'Capex'),
        (OPEX, 'Opex'),
    ]
    type = models.CharField(
        max_length=5,
        choices=TYPE_CHOICES,
        default=CAPEX,
    )

    def __str__(self):
        return self.budget_title

    class Meta:
        verbose_name = 'Presupuesto'
        ordering = ['budget_title']

class Todo(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    todo_title = models.CharField(max_length=200, verbose_name='Titulo')
    slug = AutoSlugField(populate_from='todo_title', always_update=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    deadline_date = models.DateField(null=True, verbose_name='Fecha planificación')
    collaborator = models.ForeignKey(Collaborator, on_delete=models.CASCADE, verbose_name='Encargado',null=True, blank=True)
    done_date = models.DateField(null=True, verbose_name='Fecha termino', blank=True)
    state = models.BooleanField(blank=True, null=True, default=False, verbose_name='Terminado')
    progress = models.IntegerField(blank=True, null=True, default=0)
    ordering_position = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.todo_title

    class Meta:
        verbose_name = 'Tareas de Proyecto'
        ordering = ['ordering_position']

    def diff_days(self):
        delta = self.deadline_date - self.done_date
        # print(delta.days)
        return delta.days > -5

class Milestone(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    milestone_title = models.CharField(max_length=200, verbose_name='Titulo')
    slug = AutoSlugField(populate_from='milestone_title', always_update=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    deadline_date = models.DateField(null=True, blank=True, verbose_name='Fecha planificación')
    collaborator = models.ForeignKey(Collaborator, on_delete=models.CASCADE, verbose_name='Encargado',null=True, blank=True)
    done_date = models.DateField(null=True, verbose_name='Fecha termino', blank=True)
    state = models.BooleanField(blank=True, null=True, default=False, verbose_name='Terminado')
    progress = models.IntegerField(blank=True, null=True, default=0)
    ordering_position = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.milestone_title

    class Meta:
        verbose_name = 'Hitos de Proyecto'
        ordering = ['ordering_position']

class Risknote(models.Model):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE, null=True, blank=True)
    info = models.TextField(blank=True, null=True, verbose_name = 'Información')
    slug = AutoSlugField(populate_from='info', always_update=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name = 'Asignado a')
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.info

    class Meta:
        verbose_name = 'Riesgos|Condiciones'
        ordering = ['id']

class Note(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    note_title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='note_title', always_update=True)
    body = HTMLField()
    pub_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.note_title

    class Meta:
        verbose_name = 'Nota'
        ordering = ['-id']

class File(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    repository = models.URLField(max_length=1000, null=True, blank=True)
    project_slug = AutoSlugField(populate_from='project', always_update=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def directory_path(instance, filename):
        return 'files_project/project_{0}/{1}'.format(instance.project_slug, filename)

    upload = models.FileField(upload_to=directory_path, null=True)

    def __str__(self):
        return self.repository

    class Meta:
        verbose_name = 'Repositorio documentos'
        ordering = ['id']

application/cmapp/forms.py
from django import forms
from .models import *
from datetime import datetime
from bootstrap_datepicker_plus import DatePickerInput

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('project_title', 'year', 'area', 'collaborator', 'category', 'resume', 'planned_date')

    area = forms.ModelMultipleChoiceField(
        label = 'Areas involucradas',
        queryset=Area.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    # state = forms.ChoiceField(
    #     label = 'Estado',
    #     choices = [('no_iniciado', 'No inciado'),
    #                   ('iniciado', 'Iniciado'),
    #                   ('retrasado', 'Retrasado'),
    #                   ('terminado', 'Terminado')],
    #     widget = forms.RadioSelect,
    # )

    def possible_years(first_year_in_scroll, last_year_in_scroll):
        p_year = []
        for i in range(first_year_in_scroll, last_year_in_scroll, -1):
            p_year_tuple = str(i), i
            p_year.append(p_year_tuple)
        return p_year

    year = forms.ChoiceField(
        choices=possible_years(((datetime.now()).year), 2010),
        label='Año proyecto',
    )

    # widgets = {
    #         'planned_date': DatePickerInput(),
    #     }

    planned_date = forms.DateField(
        widget=DatePickerInput(format='%d/%m/%Y')
    )

    # collaborator = forms.ModelMultipleChoiceField(
    #     label = 'Especialistas',
    #     queryset=Collaborator.objects.all(),
    #     widget=forms.CheckboxSelectMultiple
    # )

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'

    todo_title = forms.CharField(initial='Ingresa un titulo')

class RisknoteForm(forms.ModelForm):
    class Meta:
        model = Risknote
        fields = ['todo', 'user', 'info',]

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['project', 'note_title', 'body']


class BudgetForm(forms.ModelForm):
    class Meta:
        model = Budget
        fields = '__all__'

application/cmapp/templates/base_template.html
{% load static %}

{% url 'project:projects' as projects %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>PROMET {% block ttl %}{% endblock %}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'resume/favicon.png' %}" />
  <!-- Font Awesome icons (free version)-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/fontawesome.min.css">
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'resume/css/styles2.css' %}" rel="stylesheet" />

  <style media="screen">
    tr {
      border-top: hidden;
      color: white;
    }

    .table_todo_project {
      border: 1px solid #bb105a;
    }

    .table_todo_project th,
    td {
      padding: 5px;
      font-weight: normal;
    }

    td {
      background-color: #0a1424;
      color: #6C757D;
    }

    .offscreen {
      position: absolute;
      left: -999em;
    }

    img {
      max-width: 100%;
      max-height: 100%;
    }

    pre {
      background-color: #f1f1f1;
      padding: 10px;
      max-width: 865px;
      max-height: 540px;
    }

    progress {
      padding: 10px;
      width: 100%;
    }

    .toast {
      max-width: 100%;
    }

    .progress {
      height: 25px;
    }

    .massive-font {
      font-size: 25px;
    }

    .bgr-lef {
      background-color: #bb105a;
      color: white;
    }

</style>

{% block style %}{% endblock %}

</head>

<body id="page-top">
  <div class="container">

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
      <h3>
        <a href="{% url 'project:projects' %}" style="color:white">PRO<span class="text-white">MET</span></a>
      </h3>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
          class="navbar-toggler-icon"></span></button>
      {% block nav %}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          {% block ul %}

          <li class="nav-item"><a class="nav-link js-scroll-trigger {% if request.path == projects %} active{% endif %}" href="{% url 'project:projects' %}">Proyectos</a></li>



          {% endblock %}
          {% if user.is_authenticated %}
          <li class="nav-item">
            <div class="alert bg-light" role="alert">
              Conectado como <span style="color:#bb105a">{{ user.username }}</span>
              <a href="{% url 'logout' %}"><i class="fa fa-sign-out-alt"></i></a>
            </div>
          </li>
          {% else %}
          <li class="nav-item"><a class="nav-link js-scroll-trigger active" href="{% url 'login' %}"><i class="fa fa-sign-in-alt"></i> Iniciar Sesión</a></li>
          {% endif %}
        </ul>

      </div>
      {% endblock %}



    </nav>
    <!-- Page Content-->
    <div class="container-fluid p-0">
      <!-- About-->
      {% block title %}
        {% block search %}

        {% endblock %}
      {% endblock %}

    </div>
  </div>
  <!-- Bootstrap core JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
  <!-- Third party plugin JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <!-- Core theme JS-->
  <script src="{% static 'resume/js/scripts.js' %}"></script>
  <script type="text/javascript">
    function pass() {
      var copyText = document.getElementById("toCopy");
      copyText.select();
      document.execCommand("Copy");
    }
  </script>
  <script>
    $(document).ready(function() {
      $(".toast").toast('show');
    });
  </script>
  <script>
    window.onload = function() {
      document.getElementById("audio").play();
    }
  </script>
  <script>
    $(function() {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
  {% block js %}{% endblock %}
</body>

</html>

application/cmapp/templates/note_update.html
{% extends 'base_template.html' %}
{% load humanize %}
{% load static %}
{% load crispy_forms_tags %}

application/cmapp/templates/project_create.html
{% extends 'base_template.html' %}
{% load crispy_forms_tags %}



{% block title %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

<section class="resume-section" id="about">
  <div class="resume-section-content">
    <h2 class="mb-0">
      <span style="color:#bb105a">.Agregar Proyecto nuevo
    </h2>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Crear</button>
    </form>
  </div>
</section>
{% endblock %}


{% block js %}
<!-- <script src="//cdn.ckeditor.com/4.4.7/full-all/ckeditor.js"></script>
<script type="text/javascript">
  CKEDITOR.replace( 'resume' );
  CKEDITOR.config.extraPlugins = 'codesnippet';
  CKEDITOR.config.height = 400;

  $(document).ready(function() {
      $('.dateinput').datepicker({ format: "yyyy/mm/dd" });
  });
</script> -->
{% endblock %}

application/cmapp/templates/project_list.html
{% extends 'base_template.html' %}
{% load humanize %}
{% load widget_tweaks %}
{% load my_tags %}

{% block title %}
<section class="resume-section" id="about">

  <div class="resume-section-content">
    <h2 style="margin-top: 0">.Lista de Proyectos</h2>

      <!-- -->
      <div class="jumbotron bg-dark">
      <form method="get">
        <div class="well">
          <!-- <h3 style="margin-top: 0"><a href="{% url 'project:projects' %}">.Filtro</a></h3> -->
          <div class="row">
            <div class="form-group col-sm-4 col-md-3">
              <h5>Titulo</h5>
              {% render_field filter.form.project_title class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-3">
              <h5>Especialista</h5>
              <select class="custom-select mr-sm-2" name="collaborator" id="id_collaborator">
                {% for collaborator in filter.form.collaborator %}
                  <label class="checkbox-inline" value="{{ collaborator.tag }}">
                    {{ collaborator.tag }} {{ collaborator.choice_label }}
                  </label>
                {% endfor %}
              </select>
            </div>
            <div class="form-group col-sm-4 col-md-3">
              <h5>Area</h5>
              <select class="custom-select mr-sm-2" name="area" id="id_area">
                  <label class="checkbox-inline">
                    <option value="">---------</option> ---------
                  </label>
                {% for area in filter.form.area %}
                  <label class="checkbox-inline">
                    {{ area.tag }} {{ area.choice_label }}
                  </label>
                {% endfor %}
              </select>
            </div>
            <div class="form-group col-sm-4 col-md-3">
              <h5>Estado</h5>
              <select class="custom-select mr-sm-2" name="state" id="id_state">
                {% for state in filter.form.state %}
                  <label class="checkbox-inline">
                    {{ state.tag }} {{ state.choice_label }}
                  </label>
                {% endfor %}
              </select>
            </div>
          </div>
          <button type="submit" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-search"></span> Buscar
          </button>
        </div>
      </form>
      </div>

      <a class="text-info" href="{% url 'admin:cmapp_project_add' %}" target="_blank"> Crear nuevo proyecto <i class="fa fa-plus"></i></a>

      <hr class="m-0" />
      <br>


    {% for project in object_list %}
    <a href="{% url 'project:projectdetail' project.slug %}">
      <h3 class="mb-0">
        <span style="color:#bb105a">.Proyecto

        </span>{{ project.project_title }}
        {% if project.todo_done == None %}

        {% else %}
          <div class="progress">
              {% if project.todo_done == 100 %}
              <div class="progress-bar progress-bar-striped progress-bar-animated massive-font"
                   role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0"
                   aria-valuemax="100">
                  Proyecto completado
              </div>
              {% else %}
              <div class="progress-bar progress-bar-striped progress-bar-animated massive-font"
                   role="progressbar" style="width: {{project.todo_done|floatformat:0|intcomma}}%"
                   aria-valuenow="{{project.todo_done|floatformat:0|intcomma}}" aria-valuemin="0"
                   aria-valuemax="100">
                  {{ project.todo_done|floatformat:0|intcomma}}%
              </div>
              {% endif %}
              <div class="progress-bar massive-font bgr-lef" role="progressbar"
                   style="width: {{project.todo_left|floatformat:0|intcomma}}%"
                   aria-valuenow="{{project.todo_left|floatformat:0|intcomma}}" aria-valuemin="0"
                   aria-valuemax="100">
              </div>
          </div>
        {% endif %}
      </h3>
    </a>

    <div class="subheading mb-5">
      Áreas:
      {% for area in project.area.all %}
      {% if not forloop.first %}<span style="color:white"> -</span> {% endif %}
      {{ area }}
      {% endfor %}
      <br>
      Categorias:
      {% for cat in project.category.all %}
      {% if not forloop.first %}<span style="color:white"> -</span> {% endif %}

      {{ cat }}
      {% endfor %}
      <br>
      Especialista/s:
      {% for collaborator in project.collaborator.all %}
      {% if not forloop.first %}<span style="color:white"> -</span> {% endif %}
      {{ collaborator }}
      {% endfor %}
<hr class="m-0 text-light" />
<!--      <i class="fa fa-caret-right"></i> {{ project.note_set.all.count }} Notas - {{ project.crq_set.all.count }} CRQ - {{ project.todo_set.all.count }} Tareas - {{ project.budget_set.all.count }} OTs-->
    </div>

    {% endfor %}

    <nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}"><i class="fa fa-fast-backward"></i> Primero</a></li>
    <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}"><i class="fa fa-step-backward"></i> Anterior</a></li>
    {% endif %}

    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}"><i class="fa fa-step-forward"></i> Siguiente</a></li>
    <li class="page-item"><a class="page-link" href="?{% param_replace page=paginator.num_pages %}"><i class="fa fa-fast-forward"></i> Último</a></li>
    {% endif %}
    <br>
    <br>
    </ul>
      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
</nav>

  </div>
</section>
<hr class="m-0" />
{% endblock %}

{% block js %}
<script>
  $(function () {
  $('[data-toggle="popover"]').popover()
})
</script>
{% endblock %}

application/cmapp/templates/todo_project_create.html
{% extends 'base_template.html' %}
{% load crispy_forms_tags %}



{% block title %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

<section class="resume-section" id="about">
  <div class="resume-section-content">
    <h2 class="mb-0">
      <span style="color:#bb105a">.Agregar Tareas
    </h2>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Crear</button>
    </form>
  </div>
</section>
{% endblock %}


{% block js %}
<!-- <script src="//cdn.ckeditor.com/4.4.7/full-all/ckeditor.js"></script>
<script type="text/javascript">
  CKEDITOR.replace( 'resume' );
  CKEDITOR.config.extraPlugins = 'codesnippet';
  CKEDITOR.config.height = 400;

  $(document).ready(function() {
      $('.dateinput').datepicker({ format: "yyyy/mm/dd" });
  });
</script> -->
{% endblock %}